codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%

ignore:
  - ".qlty/**"
  - "biome.json"
  - "package.json"
  - "pnpm-lock.yaml"
  - "src-tauri/Cargo.lock"

comment:
  layout: reach,diff,flags,components
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

flags:
  rust:
    paths:
      - src-tauri/src/
    carryforward: true
  typescript:
    paths:
      - src/
    carryforward: true
