pub(crate) mod agent_session_exit_observer;
pub(crate) mod agent_session_wiring;
pub(crate) mod api;
pub(crate) mod app_data_composition;
pub(crate) mod application_lifecycle;
pub(crate) mod background_worker;
pub(crate) mod client;
#[cfg(feature = "desktop")]
pub(crate) mod command;
pub(crate) mod daemon;
#[cfg(feature = "desktop")]
pub(crate) mod desktop_lifecycle;
pub(crate) mod provider_session_title;
pub(crate) mod repository_scan;
pub(crate) mod review_comments_watch;
pub(crate) mod state;
pub(crate) mod terminal_checkpoint;
pub(crate) mod terminal_surface_runtime;
pub(crate) mod wiring;
pub(crate) mod workflow_startup;

pub(crate) mod terminal_surface;
