use crate::usecase::{
    agent_session::{AgentSessionHistoryPageDto, AgentSessionItemDto},
    code_dto::{ReviewFileViewDto, ReviewSnapshotDto},
    comment::ReviewThreadDto,
    provider_dto::AgentSessionProviderDto,
    repository_dto::{BranchDto, WorktreeEntryDto},
    workflow::{
        diagnostic_dto::DiagnosticReport,
        dto::{FacetSummaryDto, WorkflowDto, WorkflowSummaryDto},
        WorkspaceNodeDetailDto,
    },
    workspace_state::dto::WorkspaceStateDto,
    workspace_tree::WorkspaceList,
};

#[derive(Debug, Clone, PartialEq)]
pub(crate) enum StateValue {
    Terminal(crate::usecase::terminal_surface::application::TerminalSurfaceStreamItem),
    RepositoryPaths(Vec<String>),
    Workspaces(WorkspaceList),
    /// 実行木と、選択している Node が画面に出す木にあるか。
    Selection(crate::domain::workspace_tree::WorkspaceTree, bool),
    NodeDetail(Option<WorkspaceNodeDetailDto>),
    AgentSession(Option<AgentSessionItemDto>),
    SessionNode(Option<String>),
    SessionHistory(AgentSessionHistoryPageDto),
    Providers(Vec<AgentSessionProviderDto>),
    Branches(Vec<BranchDto>),
    BranchBase(Option<String>),
    /// ブランチと、その worktree があるか。
    BranchStatus(Vec<(crate::domain::repository::Branch, bool)>),
    CurrentBranch(String),
    Issues(crate::usecase::fetched::Fetched<Vec<crate::domain::git_host::IssueInfo>>),
    Worktrees(Vec<WorktreeEntryDto>),
    RepositoryRoot(Option<String>),
    StartupRepository(Option<String>),
    WorkspaceState(Option<WorkspaceStateDto>),
    ReviewSnapshot(ReviewSnapshotDto),
    ReviewFileView(ReviewFileViewDto),
    ReviewThreads(Vec<ReviewThreadDto>),
    Workflows(Vec<WorkflowSummaryDto>),
    Workflow(Option<WorkflowDto>),
    WorkflowSource(Option<String>),
    Facets(Vec<FacetSummaryDto>),
    Facet(String),
    Diagnostics(DiagnosticReport),
    DesktopSettings(crate::usecase::app_config::query_service::DesktopSettingsDto),
    NotionConfig(Option<crate::usecase::notion::usecase::NotionRepoConfigDto>),
    ProviderAvailability(crate::usecase::agent_session::ProviderAvailabilitySnapshotDto),
    ExternalEditor(crate::usecase::external_editor::dto::ExternalEditorState),
    ReleashBase(Option<String>),
    WorkflowConfig(crate::usecase::app_config::query_service::WorkflowConfigDto),
    PerformanceSwitches(crate::usecase::telemetry::PerformanceSwitches),
    ProviderHookHealth(crate::usecase::provider_lifecycle::ProviderHookHealthReadResult),
    StartupOutcome(crate::usecase::application_startup::ApplicationStartupOutcome),
}
