pub(crate) mod app_data_dir;
#[cfg(feature = "desktop")]
pub(crate) mod cli_install;
#[cfg(feature = "desktop")]
pub(crate) mod desktop_restart;
pub(crate) mod file_replace;
#[cfg(feature = "desktop")]
pub(crate) mod login_item;
#[cfg(feature = "desktop")]
pub(crate) mod menu;
#[cfg(feature = "desktop")]
pub(crate) mod native_drop;
#[cfg(feature = "desktop")]
pub(crate) mod native_termination;
pub(crate) mod path_aliases;
#[cfg(feature = "desktop")]
pub(crate) mod single_instance;
#[cfg(feature = "desktop")]
pub(crate) mod tray;
#[cfg(feature = "desktop")]
pub(crate) mod window_lifecycle;
